; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = m5core2

[env]                       ; 共通設定
platform = espressif32
framework = arduino
monitor_speed = 9600

; 共有インクルード/ライブラリ（相対パス）
lib_extra_dirs = ../../shared/lib
build_flags    = -I ../../shared/include

; 外部依存（バージョン固定推奨）
lib_deps =
  m5stack/M5Unified
;   m5stack/M5GFX

[env:m5core2]
board = m5stack-core2
build_flags =
  ${env.build_flags}
  -D M5UNIFIED
  -D TARGET_M5CORE2
