; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5core2

[env]
platform = espressif32@6.5.0
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../shared/lib
build_flags = -I ../../shared/include
lib_deps = 
	m5stack/M5Unified@^0.1.15
	m5stack/M5GFX@^0.1.15
  beegee-tokyo/DHT sensor library for ESPx@^1.19

[env:m5core2]
board = m5stack-core2
build_flags = 
	${env.build_flags}
	-D M5UNIFIED
	-D TARGET_M5CORE2
